/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/basketball.glb 
Author: 24fpsboy (https://sketchfab.com/ikagogava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-eb172b5f4e544f428c2bcd8d3f067a91
Title: Basketball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Basketball(props) {
  const { nodes, materials } = useGLTF('/models/basketball.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/basketball.glb')
